-- Quiz Funnel Database Schema
-- This file contains the complete database schema for the Quiz Funnel application

-- Enable UUID extension (if needed in the future)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables if they exist (for clean setup)
DROP TABLE IF EXISTS user_answers CASCADE;
DROP TABLE IF EXISTS answer_options CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;

-- Create quizzes table
CREATE TABLE quizzes (
    quiz_id SERIAL PRIMARY KEY,
    quiz_name VARCHAR(255) NOT NULL,
    product_page_url VARCHAR(500),
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT true,
    brand_logo_url VARCHAR(500),
    color_primary VARCHAR(7), -- Hex color code
    color_secondary VARCHAR(7), -- Hex color code
    color_text_default VARCHAR(7), -- Hex color code
    color_text_hover VARCHAR(7), -- Hex color code
    quiz_start_url VARCHAR(500)
);

-- Create questions table
CREATE TABLE questions (
    question_id SERIAL PRIMARY KEY,
    quiz_id INTEGER NOT NULL REFERENCES quizzes(quiz_id) ON DELETE CASCADE,
    sequence_order INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    image_url VARCHAR(500),
    interaction_type VARCHAR(50) NOT NULL,
    instructions_text VARCHAR(500),
    loader_text VARCHAR(500),
    popup_question TEXT
);

-- Create answer_options table
CREATE TABLE answer_options (
    option_id SERIAL PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,
    option_text VARCHAR(500) NOT NULL,
    associated_value VARCHAR(100) NOT NULL,
    option_image_url VARCHAR(500)
);

-- Create user_sessions table
CREATE TABLE user_sessions (
    session_id INTEGER PRIMARY KEY,
    quiz_id INTEGER NOT NULL REFERENCES quizzes(quiz_id) ON DELETE CASCADE,
    start_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_question_viewed INTEGER REFERENCES questions(question_id),
    is_completed BOOLEAN DEFAULT false,
    final_profile VARCHAR(100),
    utm_params JSONB
);

-- Create user_answers table
CREATE TABLE user_answers (
    answer_id INTEGER PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES user_sessions(session_id) ON DELETE CASCADE,
    question_id INTEGER NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,
    selected_option_id INTEGER NOT NULL REFERENCES answer_options(option_id) ON DELETE CASCADE,
    answer_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX idx_questions_quiz_id ON questions(quiz_id);
CREATE INDEX idx_questions_sequence_order ON questions(sequence_order);
CREATE INDEX idx_answer_options_question_id ON answer_options(question_id);
CREATE INDEX idx_user_sessions_quiz_id ON user_sessions(quiz_id);
CREATE INDEX idx_user_sessions_start_timestamp ON user_sessions(start_timestamp);
CREATE INDEX idx_user_sessions_utm_params ON user_sessions USING GIN (utm_params);
CREATE INDEX idx_user_answers_session_id ON user_answers(session_id);
CREATE INDEX idx_user_answers_question_id ON user_answers(question_id);

-- Add constraints
ALTER TABLE questions ADD CONSTRAINT unique_quiz_sequence UNIQUE (quiz_id, sequence_order);
ALTER TABLE user_sessions ADD CONSTRAINT check_session_id_positive CHECK (session_id > 0);
ALTER TABLE user_answers ADD CONSTRAINT check_answer_id_positive CHECK (answer_id > 0);

-- Add comments for documentation
COMMENT ON TABLE quizzes IS 'Stores quiz definitions and configuration';
COMMENT ON TABLE questions IS 'Stores questions for each quiz';
COMMENT ON TABLE answer_options IS 'Stores answer options for each question';
COMMENT ON TABLE user_sessions IS 'Tracks user quiz sessions and progress';
COMMENT ON TABLE user_answers IS 'Stores user answers for each question';

COMMENT ON COLUMN quizzes.color_primary IS 'Primary color hex code (e.g., #FF5733)';
COMMENT ON COLUMN quizzes.color_secondary IS 'Secondary color hex code (e.g., #33FF57)';
COMMENT ON COLUMN quizzes.color_text_default IS 'Default text color hex code';
COMMENT ON COLUMN quizzes.color_text_hover IS 'Hover text color hex code';
COMMENT ON COLUMN questions.interaction_type IS 'Type of interaction (multiple_choice, single_choice, etc.)';
COMMENT ON COLUMN user_sessions.session_id IS 'Unique session identifier (generated by application)';
COMMENT ON COLUMN user_sessions.utm_params IS 'JSONB object storing all UTM parameters (utm_source, utm_campaign, utm_medium, utm_term, utm_content, and any custom utm_* parameters)';
COMMENT ON COLUMN user_answers.answer_id IS 'Unique answer identifier (generated by application)';

